# Generated by Django 3.1 on 2020-08-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_of_srvc', models.CharField(blank=True, max_length=100)),
                ('inc_fr_brs', models.CharField(blank=True, max_length=100)),
                ('bsns_exp_acrd', models.CharField(blank=True, max_length=100)),
                ('bsns_exp_pd', models.CharField(blank=True, max_length=100)),
                ('prchs_of_mtrls', models.CharField(blank=True, max_length=100)),
                ('pmnt_to_splrs', models.CharField(blank=True, max_length=100)),
                ('wrtf_of_mtrls', models.CharField(blank=True, max_length=100)),
                ('rnmrtn_for_prfmrs', models.CharField(blank=True, max_length=100)),
                ('pmnt_of_rmnt', models.CharField(blank=True, max_length=100)),
                ('prdctn_csts_acrd', models.CharField(blank=True, max_length=100)),
                ('prdctn_csts_pd', models.CharField(blank=True, max_length=100)),
                ('eqpmnt_prchs', models.CharField(blank=True, max_length=100)),
                ('eqpmnt_pmnt', models.CharField(blank=True, max_length=100)),
                ('dprctn_of_eqpmnt', models.CharField(blank=True, max_length=100)),
                ('admn_expns_chrgd', models.CharField(blank=True, max_length=100)),
                ('admn_expns_pd', models.CharField(blank=True, max_length=100)),
                ('txs_chrgd', models.CharField(blank=True, max_length=100)),
                ('txs_pd', models.CharField(blank=True, max_length=100)),
                ('lns_rcvd', models.CharField(blank=True, max_length=100)),
                ('lns_rpd', models.CharField(blank=True, max_length=100)),
                ('intrsts_wrtoff', models.CharField(blank=True, max_length=100)),
                ('wthdrwls_of_ownrs', models.CharField(blank=True, max_length=100)),
                ('ownrs_invstmnts', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
