# Generated by Django 3.1 on 2020-08-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='exp_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
